### ISSUE TITLE
Can't quite get SIRVsuite to run

### ISSUE THREAD

**Issue by jamlover** [Lexogen-Tools/SIRVsuite#1]
Hi. I have been banging my head against the wall trying to get SIRVsuite running but have ahd no luck so I thought I'd see if you have any ideas on a solution.  I tried installing it a couple ways and I thought I had acheieved success, but when I try to run SIRVsuite (installed in a virtual envrionment using pip3 install), I get the following error when trying to bring up the help screen.
(sirvsuite) [jmartins@d2626ujmartins4 bin]$ python3 SIRVsuite -h
Traceback (most recent call last):
  File "SIRVsuite", line 11, in <module>
    load_entry_point('SIRVsuite==0.1.2.post0+gf0800a1.d20220427', 'console_scripts', 'SIRVsuite')()
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/SIRVsuite-0.1.2.post0+gf0800a1.d20220427-py3.6.egg/SIRVsuite/__main__.py", line 2, in <module>
    from SIRVsuite.SIRVsuite import main # pragma: no cover
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/SIRVsuite-0.1.2.post0+gf0800a1.d20220427-py3.6.egg/SIRVsuite/SIRVsuite.py", line 7, in <module>
    from SIRVsuite.Pipeline.Coverage.SIRVset_coverage import SIRVsuiteCoverage
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/SIRVsuite-0.1.2.post0+gf0800a1.d20220427-py3.6.egg/SIRVsuite/Pipeline/Coverage/SIRVset_coverage.py", line 11, in <module>
    from . import cairoDrawer as draw
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/SIRVsuite-0.1.2.post0+gf0800a1.d20220427-py3.6.egg/SIRVsuite/Pipeline/Coverage/cairoDrawer.py", line 1, in <module>
    import cairo
  File "/data/progs/sirvsuite/lib64/python3.6/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /data/progs/anaconda2/lib/./libpng16.so.16)

I am running RedHat 7 and as far as I can tell the "approved" version of zlib for that platform only goes as high as 1.2.7. I tried upgrading (which maybe I shouldn't have even tried) to 1.2.11 by downloading an rpm package and installing that, but that didn't work at all (which again, may be a good thing for my system).

I have a pretty limited skill set for this kind of thing, and I am currently out of ideas. If you have any thoughts on what I might try to being able to run SIRVsuite it would be greatlyt appreciated. My data is all set to be analyzed, I just need a working program.

Thanks,
John Martinson
USEPA
Cincinnati

**Comment by jamlover** [comment]
Tomáš,

I followed  these instructions:

#### a) PyPI
You can install SIRVsuite from GitHub by executing:
```
pip3 install git+https://github.com/Lexogen-Tools/SIRVsuite
```
It is recommended to create a python virtual environment or conda environment with python version 3.6-3.8 first. To create a python virtual environment, you can execute:
```
python3.6 -m venv sirvsuite
source sirvsuite/bin/activate
```
Once the sirvsuite venv has been created and activated, run the following commands to prepare the virtual env for installation:
```
pip3 install --upgrade pip
pip3 install numpy==1.19.2
```
Now, you can install SIRVsuite via:
```
pip3 install SIRVsuite

###########

I don't think I modified the content of the package in any way. While doing the steps above though I did run into some issues with cairo/pycairo, so I did end up installing/reinstalling those before I finally got "pip3 install SIRVsuite" to work. For what it is worth, here is what the output from the install command looks like right now...

########
pip3 install SIRVsuite
Requirement already satisfied: SIRVsuite in ./sirvsuite/lib/python3.6/site-packages/SIRVsuite-0.1.2.post0+gf0800a1.d20220427-py3.6.egg (0.1.2.post0+gf0800a1.d20220427)
Requirement already satisfied: cycler==0.10.0 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (0.10.0)
Requirement already satisfied: gtfparse==1.2.1 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (1.2.1)
Requirement already satisfied: kiwisolver==1.2.0 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (1.2.0)
Requirement already satisfied: matplotlib==3.3.1 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (3.3.1)
Requirement already satisfied: numpy==1.19.2 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (1.19.2)
Requirement already satisfied: pandas==1.1.3 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (1.1.3)
Requirement already satisfied: pyBigWig==0.3.18 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (0.3.18)
Requirement already satisfied: pycairo==1.20.0 in ./sirvsuite/lib/python3.6/site-packages (from SIRVsuite) (1.20.0)
Requirement already satisfied: pyparsing==2.4.7 in ./sirvsuite/lib/python3.6/site-packages/pyparsing-2.4.7-py3.6.egg (from SIRVsuite) (2.4.7)
Requirement already satisfied: pysam==0.16.0.1 in ./sirvsuite/lib/python3.6/site-packages/pysam-0.16.0.1-py3.6-linux-x86_64.egg (from SIRVsuite) (0.16.0.1)
Requirement already satisfied: python-dateutil==2.8.1 in ./sirvsuite/lib/python3.6/site-packages/python_dateutil-2.8.1-py3.6.egg (from SIRVsuite) (2.8.1)
Requirement already satisfied: pytz==2020.1 in ./sirvsuite/lib/python3.6/site-packages/pytz-2020.1-py3.6.egg (from SIRVsuite) (2020.1)
Requirement already satisfied: scipy==1.5.2 in ./sirvsuite/lib/python3.6/site-packages/scipy-1.5.2-py3.6-linux-x86_64.egg (from SIRVsuite) (1.5.2)
Requirement already satisfied: six==1.15.0 in ./sirvsuite/lib/python3.6/site-packages/six-1.15.0-py3.6.egg (from SIRVsuite) (1.15.0)
Requirement already satisfied: certifi>=2020.06.20 in ./sirvsuite/lib/python3.6/site-packages (from matplotlib==3.3.1->SIRVsuite) (2021.10.8)
Requirement already satisfied: pillow>=6.2.0 in ./sirvsuite/lib/python3.6/site-packages (from matplotlib==3.3.1->SIRVsuite) (8.4.0)
###########

I haven't used Docker before but maybe it's time to finally make that move. At the same time I'd love to get my current set-up working (I feel like it must be close) if I could, so if you have any other thoughts, please let me know.

Thanks,
John

**Comment by jamlover** [comment]
Tomáš,

I am no longer a non-Docker-ite. I went the Docker route as you suggested and it looks like I am now up and running. Thanks for the quick response and effective suggestion. I will now close the issue.

John
