### ISSUE TITLE
SIRVsuite KeyError: 'ERCC-00002'

### ISSUE THREAD

**Issue by EvaMarkovic** [Lexogen-Tools/SIRVsuite#4]
Hi! 

I have been trying to run SIRVsuite but I'm having problems with the --ERCC-correlation module which won't run.  The --SIRV-concentration module ran with no issues. Here is the error I'm getting: 

```
SIRVsuite -i sample_metadata.csv -o . --ERCC-correlation --coverage --experiment-name Proasellus
2024-08-11 11:57:32 INFO     helper: reading sample sheet
2024-08-11 11:57:32 INFO     ERCC_correlation: calculating correlation of ERCC spike-in ratios
Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/csic/gfy/mcs/eva/programs/SIRVsuite/sirvsuite/bin/SIRVsuite", line 8, in <module>
    sys.exit(main())
  File "/mnt/lustre/scratch/nlsas/home/csic/gfy/mcs/eva/programs/SIRVsuite/sirvsuite/lib/python3.7/site-packages/SIRVsuite/SIRVsuite.py", line 83, in main
    module_correlation = ERCCcorrelation(sample_sheet=input_dict["ERCC-correlation"], output_dir=out)
  File "/mnt/lustre/scratch/nlsas/home/csic/gfy/mcs/eva/programs/SIRVsuite/sirvsuite/lib/python3.7/site-packages/SIRVsuite/Pipeline/Correlation/ERCC_correlation.py", line 24, in __init__
    self.ERCC_correlation(cnts, output_dir=os.path.join(output_dir,"correlation/"), experiment_name = experiment_name)
  File "/mnt/lustre/scratch/nlsas/home/csic/gfy/mcs/eva/programs/SIRVsuite/sirvsuite/lib/python3.7/site-packages/SIRVsuite/Pipeline/Correlation/ERCC_correlation.py", line 65, in ERCC_correlation
    y = [cnt_data[ctrl][0] for ctrl in sorted(ERCC_conc.keys())]
  File "/mnt/lustre/scratch/nlsas/home/csic/gfy/mcs/eva/programs/SIRVsuite/sirvsuite/lib/python3.7/site-packages/SIRVsuite/Pipeline/Correlation/ERCC_correlation.py", line 65, in <listcomp>
    y = [cnt_data[ctrl][0] for ctrl in sorted(ERCC_conc.keys())]
KeyError: 'ERCC-00002'
```

**Comment by entzian** [comment]
Dear @EvaMarkovic,
thanks for the issue. I guess the entry 'ERCC-00002' is not in one of your count files. You could either create an entry in the count file with count 0 or change the line in the code 'cnt_data[ctrl]' to something like 'cnt_data.get(ctrl, 0)'.
We will investigate this issue and fix the code soon. I will leave the ticket open.

Best regards,
Gregor

**Comment by lubitelpospat** [comment]
Hi @entzian,
I'm encountering the same error, on Master branch - any updates on this?

**Comment by entzian** [comment]
Dear @lubitelpospat,
your counts file must contain an entry for 'ERCC-00002'.
Before computing the alignment and the counts, you must merge the SIRV .gtf file with the one for your annotation and the SIRV .fasta file with the fasta file for your organism.
I will implement a corresponding error message soon.
